#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

ENV_FILE="${PLATFORM_ENV_FILE:-/opt/mongodb-platform/.env}"
LOCK_FILE="${BACKUP_LOCK_FILE:-/run/lock/mongodb-platform-backup.lock}"

die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || die "run this command as root"
[[ -r "$ENV_FILE" ]] || die "cannot read $ENV_FILE"

set -a
# The production env file is root-owned and generated by install.sh.
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${MONGO_ROOT_USERNAME:?missing MONGO_ROOT_USERNAME in $ENV_FILE}"
: "${MONGO_ROOT_PASSWORD:?missing MONGO_ROOT_PASSWORD in $ENV_FILE}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/mongodb-platform}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-14}"
[[ "$BACKUP_RETENTION_DAYS" =~ ^[1-9][0-9]*$ ]] || die "BACKUP_RETENTION_DAYS must be a positive integer"

command -v mongodump >/dev/null || die "mongodump is not installed"
command -v flock >/dev/null || die "flock is not installed"
install -d -m 0700 -o root -g root "$BACKUP_DIR"
exec 9>"$LOCK_FILE"
flock -n 9 || die "another backup or restore is already running"

tool_config=$(mktemp /run/mongodb-platform-tools.XXXXXX)
partial=""
cleanup() {
  rm -f "$tool_config"
  [[ -z "$partial" ]] || rm -f "$partial"
}
trap cleanup EXIT INT TERM
cat >"$tool_config" <<EOF
uri: mongodb://${MONGO_ROOT_USERNAME}@127.0.0.1:27017/admin?authSource=admin
password: ${MONGO_ROOT_PASSWORD}
EOF
chmod 0600 "$tool_config"

stamp=$(date -u +%Y%m%dT%H%M%SZ)
archive="$BACKUP_DIR/mongodb-platform-$stamp.archive.gz"
partial="$archive.partial"
mongodump --config="$tool_config" --archive="$partial" --gzip
mv "$partial" "$archive"
partial=""
sha256sum "$archive" >"$archive.sha256"

find "$BACKUP_DIR" -maxdepth 1 -type f \
  \( -name 'mongodb-platform-*.archive.gz' -o -name 'mongodb-platform-*.archive.gz.sha256' \) \
  -mtime "+$BACKUP_RETENTION_DAYS" -delete
printf 'Backup created: %s\n' "$archive"
